project_id = "rbmepcfznvcskxayuisp"

[functions.knowledge-qa]
verify_jwt = false

[functions.generate-learning-modules]
verify_jwt = true

[functions.generate-heygen-video]
verify_jwt = false

[functions.check-heygen-video]
verify_jwt = false